name: "React CI-CD build file"

on:
  push:
    branches:
      - develop

jobs:
  frontend-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js for frontend
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install frontend dependencies
        run: yarn
        working-directory: ./frontend

      - name: Build frontend project
        run: yarn build
        working-directory: ./frontend

  backend-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js for backend
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install backend dependencies
        run: yarn
        working-directory: ./backend

      - name: Build backend project
        run: yarn build
        working-directory: ./backend

  
  
  docker_build:
    runs-on: ubuntu-latest
    needs: [frontend-build, backend-build]

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build frontend Docker image
        run: |
          docker build -f frontend/Dockerfile -t v3n0m11/frontend_image ./frontend
          
      - name: Build backend Docker image
        run: |
          docker build -f backend/Dockerfile -t v3n0m11/backend_image ./backend
      
      - name: Push frontend Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend_image

      - name: Push backend Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/backend_image