name: "MERN CI-CD Deploy File"

on:
  pull_request:
    branches:
      - main

jobs:
  kubernetes_deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Configure AWS credentials using the IAM role
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::203918850897:user/eksAdmin
          aws-region: ap-south-1

      # Update kubeconfig for Kubernetes cluster access
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region ap-south-1 --name mini_eks --role-arn arn:aws:iam::203918850897:user/eksAdmin

      # Debug Kubernetes Configuration
      - name: Debug Kubernetes Configuration
        run: |
          kubectl config view
          kubectl cluster-info
          kubectl get nodes

      # Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      # Verify Deployment
      - name: Verify Deployment
        run: |
          kubectl rollout status deployment/react-frontend
