name: "MERN CI-CD deploy file"

on:
  pull_request:
    branches:
      - main

jobs:
  kubernetes_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.22.0'  # Adjust based on your cluster version

      - name: Configure Kubernetes Credentials
        run: |
          echo "${{ secrets.KUBERNETES_CA_CERT }}" | base64 -d > ca.crt
          kubectl config set-cluster eks-cluster --server=${{ secrets.KUBERNETES_SERVER_URL }} --certificate-authority=ca.crt
          kubectl config set-credentials github-actions --token=${{ secrets.KUBERNETES_TOKEN }}
          kubectl config set-context eks-context --cluster=eks-cluster --user=github-actions
          kubectl config use-context eks-context

      - name: Debug Kubernetes Configuration
        run: |
          kubectl config view
          kubectl cluster-info
          kubectl get nodes

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      - name: Verify Deployment
        run: |
          kubectl rollout status deployment/react-frontend
