name: Image push and K8s deploy

on:
  pull_request:
    branches:
      - main  # Trigger on pull request targeting the main branch

jobs:
  docker_build:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build frontend Docker image
        run: |
          docker build -f frontend/Dockerfile -t v3n0m11/frontend_image ./frontend
      - name: Build backend Docker image
        run: |
          docker build -f backend/Dockerfile -t v3n0m11/backend_image ./backend
      - name: Push frontend Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend_image
      - name: Push backend Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/backend_image
          
  kubernetes-rollout:
    runs-on: ubuntu-latest  # Runner environment

    steps:
      # Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up AWS CLI with AWS credentials from GitHub secrets
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Set up kubectl
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      # Configure kubectl using AWS CLI (No need for manual KUBECONFIG setup)
      - name: Configure kubectl with EKS credentials
        run: |
          aws eks update-kubeconfig --name mini_eks --region ${{ secrets.AWS_REGION }}

      # Rollout restart the Kubernetes deployment to use the latest image
      - name: Rollout restart for deployment
        run: kubectl rollout restart deployment react-frontend
