name: Kubernetes Rollout on Docker Image Push

on:
  pull_request:
    branches:
      - main  # Trigger on pull request targeting the main branch

jobs:
  kubernetes-rollout:
    runs-on: ubuntu-latest  # Runner environment

    steps:
      # Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up AWS CLI with AWS credentials from GitHub secrets
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Set up kubectl
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      # Configure kubectl using AWS CLI (No need for manual KUBECONFIG setup)
      - name: Configure kubectl with EKS credentials
        run: |
          aws eks update-kubeconfig --name your-cluster-name --region ${{ secrets.AWS_REGION }}

      # Rollout restart the Kubernetes deployment to use the latest image
      - name: Rollout restart for deployment
        run: kubectl rollout restart deployment react-frontend
