name: Kubernetes Rollout on Docker Image Push

on:
  pull_request:
      - main

jobs:
  kubernetes-rollout:
    runs-on: ubuntu-latest  # Runner environment

    steps:
      # Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up kubectl
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      # Set KUBECONFIG from GitHub secret and save it as a file
      - name: Set KUBECONFIG from secret
        run: echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      # Rollout restart the Kubernetes deployment to use the latest image
      - name: Rollout restart for deployment
        run: kubectl rollout restart deployment react-frontend
